version: "3.9"
services:
  psql:
    image: postgres:latest
    container_name: online-store-postgres
    restart: always
    environment:
      POSTGRES_USER: sixojke
      POSTGRES_PASSWORD: sixojke
      POSTGRES_DB: postgres
    volumes:
      - /home/sixojke/online-store:var/lib/postgresql/data
    ports:
      - "5433:5433"